### ISSUE TITLE
Amstrad CPC TODO

### ISSUE THREAD

**Issue by floooh** [floooh/chips#5]
- [ ] CRTC detection of GFX demos doesn't work, some demos won't start because of this, or switch off effects
- [ ] Because of ^^^ the text scrolling over the 3D cube in Demoizart doesn't show because the demo doesn't detect a CRTC type 0, and doesn't update the R8 register (Interlace/Skew) to switch DE (display-enable) on/off mid screen.
- [ ] The floppy emulation hasn't implemented the Sense Drive command, this is used by some floppy loaders
- [ ] Broken scanlines in Byte'98 demo:
![screen shot 2018-12-29 at 3 55 33 pm](https://user-images.githubusercontent.com/1699414/50539531-16578800-0b82-11e9-8844-b77bd2c25fcc.png)
- [ ] various (similar?) line artifacts in the Landscape part of Demoizart:
![screen shot 2018-12-29 at 3 59 28 pm](https://user-images.githubusercontent.com/1699414/50539560-a4337300-0b82-11e9-822f-d5e81c2a25a2.png)

**Comment by floooh** [comment]
Hmm, the problem in the Byte'98 demo is caused by reloading the CRTC ma_row_start value with the start_addr registers while the demo writes a new address to the start_addr register. 

"Capturing" the next start_addr from registers at the horizontal display-end cycle (similar to the fix the backtro demo) fixes the Byte'98 demo artifacts, but breaks the DTC demo (which now has similar scanline artefacts)...

**Comment by floooh** [comment]
Ok, "phase-shifting" the 1MHz the CCLK tick in relation to the 4 MHz CPU tick fixes the line artefacts in the Byte'98 demo. This seems to be just enough that the CRTC sees the new row start address written by the CPU for a new scanline.

**Comment by floooh** [comment]
More reminders:

The phase-shift-fix above is actually not the proper fix :/ There are still various problems in the mc6845 code in regards to the vsync/hsync stuff. The "problem" in the Byte'98 demo is that the HSYNC ends exactly at the end of the line:

HTOTAL=0x3F, HSyncPos=0x32, SyncWidth=0x8E

0x32 + 0x0E is 0x40

With the current implementation, the HSync phase "spills over" into the next scanline which is clearly wrong.

The other obvious problem in some demos is that a switch between 2 display sections happens 1 scanline too late. Moving the interrupt delay one line up fixes those issues in most demos, but breaks the Twist-Part in the Demoizart demo.
